### ISSUE TITLE
Download as webm doesn't work on this one

### ISSUE THREAD

**Issue by maple3142** [leoding86/pixiv-toolkits#1]
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=65642789

**Comment by leoding86** [comment]
It's works for me. Could you provide me more infomations?

**Comment by maple3142** [comment]
https://send.firefox.com/download/c3fafb47da13cbf8/#R3lF73ptgtQmUNBkPj5bPw
The zip consists of a gif and a webm downloaded by your extension.
The gif works fine, but when I play the webm with VLC, it just stuck at the first frame.

**Comment by leoding86** [comment]
I noticed the issue, but I think there isn't much I can do. If you open the webm with Chrome, you'll find it plays really well. I think this issue is VP8 related.
I'll close it for now.

**Comment by leoding86** [comment]
I test the webm in PotPlayer and Media Player Classic. Both of them play it very well. So I suggest you to use different video player.
